### ISSUE TITLE
CMS 7.5: Record/page browser in link wizard not working

### ISSUE THREAD

**Issue by RauchF** [cobwebch/linkhandler#13] opened 2015-10-01 09:55 UTC
Sorry to be the bearer of bad news, but as mentioned in #12 , in TYPO3 CMS 7.5 the page tree in the record browser ceased working. Clicking the little arrow on the left or right of a page will cause the entire BE to be loaded in the link wizard popover (only on linkhandler tabs)

Additionally, the JS error "Uncaught TypeError: Cannot read property 'Persistent' of undefined" gets logged.

**Comment by fsuter** [comment] 2015-10-01 11:58
I am aware of that and the case is probably desperate. OTOH Markus Klein is pushing for having the linkhandler features integrated into the TYPO3 Core and I have planned to help him. Hopefully he (we) will make it, because extension linkhandler is getting desperately hard to maintain.

**Comment by fnagel** [comment] 2015-10-06 21:15
I can confirm and beweep this.

Reference to "core linkhandler in 7.x" info: https://forge.typo3.org/issues/46140#change-279888

**Comment by fsuter** [comment] 2015-10-07 08:29
Don't weep too hard, things are making progress ;-) I pushed patches yesterday about that into the Core: https://forge.typo3.org/issues/66372

It's still ongoing work, but it is clearly in the roadmap for CMS 7. And the base work laid out by Markus Klein is so good that development of a generic link handler is now really much easier.

**Comment by fnagel** [comment] 2015-10-08 10:49
Sounds good, ping me when some testing or review is needed!

**Comment by fsuter** [comment] 2015-10-08 11:30
Will do, thanks!

**Comment by AndreasA** [comment] 2015-11-17 13:48
Now that it definitely won't make it completely (although most of the API has been prepared) into 7LTS anymore, when do you plan to release an updated version.

**Comment by fsuter** [comment] 2015-11-17 13:56
Sorry for not following up before. The good news is that the API made it, so that my work will be easy to pack into extension "linkhandler". The only issue is that the RTE integration is still buggy.

I plan to work on this topic this coming Friday and check with Markus Klein what can be done with the RTE integration. So I hope to have something working very soon. But it won't work properly with TYPO3 7.6.0 (hopefully with 7.6.1 if we can manage to get the proper fix in).

**Comment by fnagel** [comment] 2015-11-17 14:10
Sounds great! Thanks for the update and all the time you put into this effort!

**Comment by AndreasA** [comment] 2015-11-18 18:55
@fsuter:
I have create a own linkhandler for a project today (the customers needed it ASAP) and I had no problem in RTE in 7.6.0 but I have already "backported" some bugfixes::
https://git.typo3.org/Packages/TYPO3.CMS.git/commit/7b3c32e76ee94ee4f57d7bc130174554f4cbc8c7
https://git.typo3.org/Packages/TYPO3.CMS.git/commit/5f67d88a8da217bf9d2aac66b9e43d0d67ec3a0c

I also included this bugfixes to get classAnchors to work again:
https://review.typo3.org/#/c/44736/

Maybe I also included this:
https://git.typo3.org/Packages/TYPO3.CMS.git/commit/48bfec32456483e5424d80a5baf58db98b3305c3

I have mine based on the LinkHandler for pages but modified for the pagetree to always expand and to use the ElemenBrowser (extended the original to e.g. use renderTableRecords directly and set some protected attributes directly) used by the link wizard instead of rendering records directly and a corresponding requireJsModule.

**Comment by fsuter** [comment] 2015-11-20 07:01
Andreas, thanks a lot for all that information. I'll take a look today.

**Comment by fsuter** [comment] 2015-11-20 07:04
The bugfixes you mention are indeed important. I guess I'll make the extension depend on 7.6.1+ and not 7.6.0.

**Comment by fsuter** [comment] 2015-11-25 17:36
I committed a lot of stuff these last few days and the master version is basically working. There's no documentation yet, but you should be fine with just looking at the files in `Configuration/TSconfig/Page` and `Configuration/TypoScript`.

Soft-reference parser and link validator parts have not been updated yet.

I have also thrown out some stuff in the cleanup process. Please open separate issues if you suddenly miss something.

**Closed by fsuter** 2015-11-25 17:36 UTC
